### ISSUE TITLE
nosetests does not match raw test script

### ISSUE THREAD

**Issue by skytreader** [skytreader/pydagogical#1]
Bug either for nosetest or for me.

This happens with commit c0ed721ae850ba5ca9b93037ace4f586d443466e.

For nose v1.3.1, look:

    (nose)ch@destioco:data_structures$ nosetests graphs.py
    F..........EEF...........
    ======================================================================
    ERROR: test_dfs_islands (data_structures.graphs.IteratorTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ch/kode/pydagogical/data_structures/graphs.py", line 758, in test_dfs_islands
        self.assertEqual(["node1"], islander("node1"))
      File "/home/ch/kode/pydagogical/data_structures/graphs.py", line 756, in <lambda>
        islander = lambda node: [n for n in DFSIslandIterator(four_single_islands, node)]
    TypeError: iter() returned non-iterator of type 'DFSIslandIterator'
    
    ======================================================================
    ERROR: test_dfs_iterator (data_structures.graphs.IteratorTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ch/kode/pydagogical/data_structures/graphs.py", line 731, in test_dfs_iterator
        dfs_result = [node for node in DFSIterator(singleset)]
    TypeError: iter() returned non-iterator of type 'DFSIterator'
    
    ======================================================================
    FAIL: get_neighbors_test (data_structures.graphs.AdjacencyListTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ch/kode/pydagogical/data_structures/graphs.py", line 596, in get_neighbors_test
        self.assertEqual(n1_expected_neighbors, set(n1_neighbors))
    AssertionError: Items in the first set but not the second:
    'node3'
    'node2'
    'node4'
    
    ======================================================================
    FAIL: get_neighbors_test (data_structures.graphs.UndirectedAdjListTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ch/kode/pydagogical/data_structures/graphs.py", line 596, in get_neighbors_test
        self.assertEqual(n1_expected_neighbors, set(n1_neighbors))
    AssertionError: Items in the first set but not the second:
    'node3'
    'node2'
    'node4'
    
    ----------------------------------------------------------------------
    Ran 25 tests in 0.002s
    
    FAILED (errors=2, failures=2)
    (nose)ch@destioco:data_structures$

**Comment by skytreader** [comment]
Must check this out again since it seems that, those logs came from before I restructured the code for nose auto-discover.

**Comment by skytreader** [comment]
Got it. This is due to using Python 2.x for Python 3 code. Really,

    self.get_some_sleep()
